language: java
jdk:
- oraclejdk8
install: true
script: gradle jar
deploy:
  provider: bintray
  file: descriptor.json
  user: tsmgodoi
  key:
    secure: JK2O7kCjQ6hnAp0K7vGCMQKKwu3vByuAPpNBI6cY846scB6GS6EyD6Jpg20P+qE20VbcjzkWlzwJ/DijWnoGbisvUsmcYVdGO2E39JttLOpDTf8vkOIqBKhbSa0/Q/CbL5e171+BD78Ex8HZqjxXWbvWvKLMAna+m8HER1L8WjU1ay4HbqM8jRndPJTssXeWOgdpUYJZwTSSrmMIoLTIMdvVs9ioBo+fDJi0G0YvMqrnH7+a7c4MXLrqsNDQgGK+NUa8cgJC3KkhW4PuE/PfX1WiRZNQQyA5619JkIYl6rx8in1t6JiewzLKZCrR20ZBo5+HHGOPZCGlQjg714gTKzfxaNxEzw6WMBThNKAXHJRLl9UzqHSmKIBidmmZPMgbLBrqPgEmd2vjJuX1Bpe/b7VhlY5el1WPa8i3duev9zoaJlE8QdrCzh7JcA3hScov9HC/t/Onw5Z6faMwgvF8/p1PVIPMjTYlCFmcd65NrbPXU+Uyu0hyj+bLjBq2BIzwl3LEUG2jmGaUryaDjCfihCf/cEzbPheFlGBycTK0CBtCp8QjzY+q9HzaLKR9Y9ibJtJpBkg0wKWNWBArsL4jsrcKPCv3KJgO0cX3rwGXUmwwJ8MOm5crTsLkqm0YefNviRuWDFvLAfFSM21IKPlEInfZV+qR/JrXvrwK2DybXUE=
notifications:
  slack:
    secure: miCQfhTka9FOH3pdDBYg2OT/Bzs2YdxptRThh93L8MtVr1PVTWisIqOLKgEeunUA5WZ1WEKoU4MFMCqZNqaQDIU3LJLNmodo/Ux63S+HCqL/KJzyEJp9Q5Ir6YNdMvwOLR2sIqdkCxb0QjFR+gOWXi8MnKdgINfFyGwspO2cAi4fHIWU+XovlLwpY3ACeV6m/zqI0agMGphxt0Eu9L/GTWjqaZtEvRs2/F2b7YWFnLOuEdSVA0+dPBIJk0aj3PgSJIShC8+cu/f4oW3VFFT85m31EIv5+BLVGfo38W0kgJ0YRFzo7VIKTQn1W79HPGra1lHywNJbvq1187X11XtpyyY6Iht2ScJVd+2h1l4AVh/XpXueTaGwMLBMTUSIYiYbs0Dl0Ndqnc3pl68A01pC5UxnUCiBYSGsMsJ7VdRbyMB2Sfo7NMl1nqo86F8YtwJdbWJ6lgI1w5K9B7YrmEwA5DPFLcHvmHB/FfxDbI5unDIylroUOG2OSgBz8OAa2bOoeWUjE4c1PfMycuahRQ7Q2+k/UmN7i7EnYXo7Z6VzrQKEGr+gZCmOeZrjJ1Lx9tFWfHe/NvojIKEEdaR1sgmJoa7zvBjxg5SSX6RLOqmLuAYZ86ZFqEaPHxE8plmKCUmgh3YHVLOnEOhJfPRmrtbymL+gquDdfN+P7rRo9YVivtc=
